<?php
// module/Album/view/proyecto/proyecto/index.phtml:

$title = 'Proyectos';
$this->headTitle($title);
?>

<!--<div class="page-header">
        <div class="row">-->

               <h1>Listado de <?php echo $this->escapeHtml($title); ?></h1></h1>
                <form action="<?php echo $this->url('proyecto',
                                    array('action'=>'add', 'id' => $proyecto->id));?>">
                    <input class="btn" type="submit" value="Nuevo proyecto">
                </form>


<table class="table table-hover">
<tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Estado</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $proyecto) : ?>
<tr>
    <td><a href="<?php echo $this->url('proyecto',
            array('action'=>'detalle', 'id' => $proyecto->id));?>"><?php echo $this->escapeHtml($proyecto->nombre);?></a></td>
    <td>
        <?php if (strlen($this->escapeHtml($proyecto->descripcion))>80) 
                                  echo substr($this->escapeHtml($proyecto->descripcion), 0, 80).'...'; 
                                else echo $this->escapeHtml($proyecto->descripcion);?>
    </td>
    <td><?php echo ($this->escapeHtml($proyecto->estado) == 1) ? 'Abierto' : 'Terminado';?></td>
    <td>
        <a href="<?php echo $this->url('proyecto',
            array('action'=>'edit', 'id' => $proyecto->id));?>">Editar</a>
        <a href="<?php echo $this->url('proyecto',
            array('action'=>'delete', 'id' => $proyecto->id));?>">Borrar</a>
    </td>
</tr>
<?php endforeach; ?>
</table> 

<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Proyecto'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'proyecto'
    )
);
?>

 
