<?php
// module/Album/view/proyecto/proyecto/delete.phtml:

$title = 'Eliminar trabajador';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>¿Eliminar definitivamente de la lista de trabajadores a  
    '<?php echo $this->escapeHtml($trabajador->nombre); ?>' con DNI <?php echo $this->escapeHtml($trabajador->dni); ?>? Todos sus datos asociados se perderán.
</p>
<?php
$url = $this->url('trabajador', array(
    'action' => 'delete',
    'dni'     => $this->dni,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="dni" value="<?php echo $trabajador->dni; ?>" />
    <input type="submit" name="del" value="Sí" class="btn btn-danger"/>
    <input type="submit" name="No" value="Pensándolo bien..." class="btn" />
</div>
</form> 
