<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Completitud del proyecto</strong>, en mi humilde opinión personal
  <div class="progress progress-striped active">
    <div class="bar" style="width: 95%;"></div>
  </div>
</div>

<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('%sFourcor%s'), '<span class="zf-green">', '</span>') ?></h1>
    <h2><?php echo sprintf($this->translate('Gestión de proyectos de edificación'), '<span class="zf-green">', '</span>') ?></h2>
   
    <p><?php echo sprintf($this->translate('Sistema para una empresa ficticia que sirve como prueba de selección. Puedes ver y descargar el código fuente desde %sGithub%s.'), '<a href="https://github.com/" target="_blank">', '</a>', 'Ver código fuente') ?></p>
    <p><a class="btn btn-primary btn-large" href="https://github.com/raprav/Fourcor" target="_blank"><?php echo $this->translate('Ver código fuente') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="span8">
        <h3><?php echo $this->translate('Integración de Frameworks') ?></h2>
        <p><?php echo sprintf($this->translate('Solución desarrollada utilizando %sZend Framework 2 (Skeleton)%s en el back-end sobre una base de datos MySQL, proporcionando un enfoque orientado a objetos implementando el patrón Modelo Vista Controlador. A su vez, implementado un front-end responsive gracias al %sTwitter Bootstrap 2.3.2%s, obteniendo una interfaz limpia, usable y multi-dispositivo.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication">', '</a>', '<a href="http://twitter.github.io/bootstrap/">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
        <p><?php echo sprintf($this->translate('Para facilitar la inserción de Bootstrap sobre la arquitectura generada por Zend Framework utilizo el módulo %sDluTwBootstrap%s, desarrollado por %sDavid Lukas%s.'), '<a href="https://bitbucket.org/dlu/dlutwbootstrap">', '</a>', '<a href="http://twitter.github.io/bootstrap/">', '</a>', '<a href="http://www.zfdaily.com/about/">', '</a>') ?></p>
    </div>

   <div class="span4 ">
      <div class="row">
        <div class="span2">
          <img src="http://i.imgur.com/QUkK5uy.jpg" class="img-polaroid">
        </div>
        <div class="span2">
          <address>
            <strong>Rafael Prats Vieira</strong><br>
            Estudiante de Grado en Ingeniería Informática, especialidad en Ingeniería del Software y Tecnologías de la Información<br>
          </address>
           
          <address>
            <strong>Contacto</strong><br>
            <a href="mailto:#">rpratsv@gmail.com</a>
          </address>
        </div>
      </div>

       <!--<p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>-->
   </div>
</div>
